api = "0.9"

[buildpack]
id = "heroku/python"
version = "0.4.0"
name = "Python"
homepage = "https://github.com/heroku/buildpacks-python"
description = "Heroku's official Python Cloud Native Buildpack."
keywords = ["python", "heroku"]
clear-env = true

[[buildpack.licenses]]
type = "BSD-3-Clause"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "heroku-22"

[metadata]
[metadata.release]
[metadata.release.docker]
repository = "docker.io/heroku/buildpack-python"
