api = "0.9"

[buildpack]
id = "heroku/python"
version = "0.7.3"
name = "Heroku Python"
homepage = "https://github.com/heroku/buildpacks-python"
description = "Heroku's buildpack for Python applications."
keywords = ["python", "heroku"]

[[buildpack.licenses]]
type = "BSD-3-Clause"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "heroku-22"

[metadata.release]
image = { repository = "docker.io/heroku/buildpack-python" }
